### ISSUE TITLE
UML and ER diagrams needed

### ISSUE THREAD

**Issue by Ben-dingo** [TGLS/4806project#8]
We need a UML and an ER diagram prepared for the project. They both should represent the master branch as it is now, then closer to March 20th, 2019 it should be updated to represent the finished milestone 2 code.

**Comment by TGLS** [comment]
This details how to install ejb support: https://www.jetbrains.com/help/idea/enabling-ejb-support.html#existing
That apparently allows autogenerated ER diagrams https://www.jetbrains.com/help/idea/ejb-module-editor-ejb-relationships.html

**Comment by LawKyle** [comment]
I will complete the Entity Relationship Model
